jms_serializer:
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
    metadata:
        auto_detection: false
        directories:
            GreenterCore:
                namespace_prefix: "Greenter\\Model"
                path: "%kernel.project_dir%/config/serializer"