jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            GreenterCore:
                namespace_prefix: "Greenter\\Model"
                path: "%kernel.project_dir%/config/serializer"