nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: []
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 0
    paths:
        '^/api':
          allow_methods: ['POST', 'GET']
          max_age: 3600
        '^/swagger':
          allow_methods: ['GET']
