nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
        paths:
            '^/api':
                allow_methods: ['POST', 'GET']
                max_age: 3600
            '^/swagger':
                allow_methods: ['GET']