Greenter\Model\Sale\Note:
    properties:
        fechaEmision:
            type: DateTime
        company:
            type: Greenter\Model\Company\Company
        client:
            type: Greenter\Model\Client\Client
        details:
            type: array<Greenter\Model\Sale\SaleDetail>
        legends:
            type: array<Greenter\Model\Sale\Legend>
        guias:
            type: array<Greenter\Model\Sale\Document>
        relDocs:
            type: array<Greenter\Model\Sale\Document>
        perception:
            type: Greenter\Model\Sale\SalePerception