Greenter\Model\Despatch\Despatch:
    properties:
        fechaEmision:
            type: DateTime
        company:
            type: Greenter\Model\Company\Company
        destinatario:
            type: Greenter\Model\Client\Client
        tercero:
            type: Greenter\Model\Client\Client
        envio:
            type: Greenter\Model\Despatch\Shipment
        docBaja:
            type: Greenter\Model\Sale\Document
        relDoc:
            type: Greenter\Model\Sale\Document
        details:
            type: array<Greenter\Model\Despatch\DespatchDetail>