Greenter\Model\Perception\Perception:
    properties:
        fechaEmision:
            type: DateTime
        company:
            type: Greenter\Model\Company\Company
        proveedor:
            type: Greenter\Model\Client\Client
        details:
            type: array<Greenter\Model\Perception\PerceptionDetail>