Greenter\Model\Summary\Summary:
    properties:
        fecGeneracion:
            type: DateTime
        fecResumen:
            type: DateTime
        company:
            type: Greenter\Model\Company\Company
        details:
            type: array<Greenter\Model\Summary\SummaryDetail>